"""
Dynamic DAG generator with YAML config system to create DAG which
searches terms in the Gazzete [Diário Oficial da União-DOU] and send it
by email to the  provided `recipient_emails` list. The DAGs are
generated by YAML config files at `dag_confs` folder.
"""

import ast
import json
import logging
import os
import sys
import textwrap
from datetime import datetime, timedelta, date
from typing import Dict, List, Optional, Union
from functools import reduce

from airflow import DAG, Dataset
from airflow.models.param import Param
from airflow.utils.task_group import TaskGroup

from airflow.operators.empty import EmptyOperator
from airflow.operators.python import BranchPythonOperator, PythonOperator

from airflow.timetables.datasets import DatasetOrTimeSchedule
from airflow.timetables.trigger import CronTriggerTimetable

sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))
from utils.date import get_trigger_date, template_ano_mes_dia_trigger_local_time
from utils.select_terms import TermSelector
from notification.notifier import Notifier
from parsers import DAGConfig, YAMLParser
from schemas import FetchTermsConfig
from searchers import BaseSearcher, DOUSearcher, QDSearcher, INLABSSearcher
from analytics.extractor import build_result_hash, extract_findings
from hooks.analytics_mariadb_hook import AnalyticsMariaDBHook

from airflow.models import Variable
from ai.runner import AIRunner
SearchResult = Dict[str, Dict[str, Dict[str, List[dict]]]]


def merge_results(*dicts: SearchResult) -> SearchResult:
    """
    Merge multiple dictionaries and sum/concatenate values of common keys,
    including nested dictionaries.
    """

    def merge_two(dict1, dict2):
        merged = {}

        # Combine keys from both dictionaries
        all_keys = set(dict1) | set(dict2)

        for key in all_keys:
            value1 = dict1.get(key)

            value2 = dict2.get(key)

            if isinstance(value1, dict) and isinstance(value2, dict):
                # If both values are dictionaries, merge them recursively
                merged[key] = merge_results(value1, value2)
            elif isinstance(value1, dict) or isinstance(value2, dict):
                # If one of the values is a dict, prefer the dict (override with dict)
                merged[key] = value1 if isinstance(value1, dict) else value2
            else:
                # Sum or concatenate the values, treating None or missing keys as 0
                merged[key] = (value1) + (value2)

        return merged

    # Pre-processing step: Filter out dictionaries where the first key's value is empty
    filtered_dicts = []

    for d in dicts:
        if d:  # Ensure the dictionary is not empty
            first_key = next(iter(d))
            first_value = d.get(first_key)
            if first_value:  # Only include if the first key's value is non-empty
                filtered_dicts.append(d)

    # If no dictionaries remain after filtering, return an empty dictionary
    if not filtered_dicts:
        return {}

    # Reduce the list of dictionaries by merging them two at a time
    return reduce(merge_two, filtered_dicts)


def result_as_html(specs: DAGConfig) -> bool:
    """Use HTML results only for emails"""
    return bool(not (specs.report.discord or specs.report.slack))


class DouDigestDagGenerator:
    """
    YAML based Generator of DAGs that digests the DOU (gazette) daily
    publication and send email report listing all documents matching
    pré-defined keywords. It's also possible to fetch keywords from the
    database.
    """

    YAMLS_DIR = os.getenv("RO_DOU__DAG_CONF_DIR")

    if YAMLS_DIR is None:
        raise EnvironmentError("Environment variable RO_DOU__DAG_CONF_DIR not found!")

    YAMLS_DIR_LIST = [dag_confs for dag_confs in YAMLS_DIR.split(":")]
    SLACK_CONN_ID = "slack_notify_rodou_dagrun"
    DEFAULT_SCHEDULE = "0 5 * * *"
    ANALYTICS_CONN_ID = "rodou_analytics_db"
    ANALYTICS_FINDINGS_TABLE = "rodou_search_findings"
    ANALYTICS_SUMMARY_TABLE = "rodou_search_term_summary"

    parser = YAMLParser
    searchers: Dict[str, BaseSearcher]

    def __init__(self):
        self.searchers = {
            "DOU": DOUSearcher(),
            "QD": QDSearcher(),
            "INLABS": INLABSSearcher(),
        }

        self.on_failure_callback = self._notify_on_failure
        self.on_retry_callback = None

    def _notify_on_failure(self, specs: DAGConfig, context):
        """Function called when the task fails to send a notification to admin"""
        from notification.failure_sender import FailureSender

        try:
            task_instance = context.get("task_instance") or context.get("ti")
            dag_run = context.get("dag_run")
            exception = context.get("exception")

            if not task_instance or not dag_run:
                logging.error("Missing required context: task_instance or dag_run")
                return

            failure_sender = FailureSender(specs=specs)
            failure_sender.send(context, dag_run, task_instance, exception)

        except Exception as e:
            logging.error(f"Error in _notify_on_failure: {str(e)}", exc_info=True)

    @staticmethod
    def prepare_doc_md(specs: DAGConfig, config_file: str) -> str:
        """Prepares the markdown documentation for a dag.

        Args:
            specs (DAGConfig): A DAG configuration object.
            config_file (str): The name of a DAG config file.

        Returns:
            str: The DAG documentation in markdown format.
        """
        config = specs.model_dump()
        # options that won't show in the "DAG Docs"
        del config["description"]
        del config["doc_md"]
        doc_md = specs.doc_md + textwrap.dedent(
            f"""

            **Configuração da dag definida no arquivo `{config_file}`**:


            """
        )
        for key, value in config.items():
            doc_md += f"\n**{key.replace('_', ' ').capitalize()}**\n"

            if isinstance(value, (list, set)):
                doc_md += "\n" + "\n".join(f"- {str(item)}" for item in value) + "\n"
            else:
                doc_md += "\n" + f"- {str(value)}\n" + "\n"

        return doc_md

    @staticmethod
    def _hash_dag_id(dag_id: str, size: int) -> int:
        """Hashes the `dag_id` into a integer between 0 and `size`"""
        buffer = 0
        for _char in dag_id:
            buffer += ord(_char)
        try:
            _hash = buffer % size
        except ZeroDivisionError:
            raise ValueError("`size` deve ser maior que 0.")
        return _hash

    def _get_safe_schedule(self, specs: DAGConfig, default_schedule: str) -> str:
        """Return a new value of `schedule`, randomazing the
        execution minute accorgind to `dag_id`, if the dag use the
        schedule standard. Apply a function of hash to string
        dag_id to return a value between 0 and 60, wich defines the execution minute.
        """

        schedule = default_schedule
        id_based_minute = self._hash_dag_id(specs.id, 60)
        schedule_without_min = " ".join(schedule.split(" ")[1:])
        schedule = f"{id_based_minute} {schedule_without_min}"

        return schedule

    def _update_schedule_with_dataset(
        self, dataset: str, schedule: str, is_default_schedule: bool
    ) -> Union[Dataset, DatasetOrTimeSchedule]:
        """If a dataset is provide, the schedule will be update
        to make execution conditional on the Dataset or
        DatasetOrTimeSchedule
        (if the value of schedule is specified in the YAML information).
        """
        if not is_default_schedule:
            return DatasetOrTimeSchedule(
                timetable=CronTriggerTimetable(
                    schedule, timezone=os.getenv("AIRFLOW__CORE__DEFAULT_TIMEZONE")
                ),
                datasets=[Dataset(dataset)],
            )
        return [Dataset(dataset)]

    def _update_schedule(
        self, specs: DAGConfig
    ) -> Union[str, Union[Dataset, DatasetOrTimeSchedule]]:
        """The DAG will update the value of schedule to
        the default value or to a Dataset, if that option is specified.
        """
        schedule = specs.schedule

        if schedule is None:
            schedule = self._get_safe_schedule(
                specs=specs, default_schedule=self.DEFAULT_SCHEDULE
            )
            is_default_schedule = True
        else:
            is_default_schedule = False

        if specs.dataset is not None:
            schedule = self._update_schedule_with_dataset(
                dataset=specs.dataset,
                schedule=schedule,
                is_default_schedule=is_default_schedule,
            )

        return schedule

    def generate_dags(self):
        """Iterates over the YAML files and creates all dags"""

        files_list = []

        for directory in self.YAMLS_DIR_LIST:
            for dirpath, _, filenames in os.walk(directory):
                for filename in filenames:
                    if any(ext in filename for ext in [".yaml", ".yml"]):
                        files_list.extend([os.path.join(dirpath, filename)])

        for filepath in files_list:
            dag_specs = self.parser(filepath).parse()
            dag_id = dag_specs.id
            globals()[dag_id] = self.create_dag(dag_specs, filepath)

    def _parse_term_list(self, term_list):
        """Converte term_list para lista, tratando aspas duplas extras."""
        if not isinstance(term_list, str):
            return term_list

        # Remove espaços
        term_list = term_list.strip()

        # Tenta converter até 2 vezes (para casos de serialização dupla)
        for _ in range(2):
            if term_list.startswith(("[", '"[', "'[")):
                try:
                    term_list = ast.literal_eval(term_list)
                    if isinstance(term_list, list):
                        return term_list
                except (ValueError, SyntaxError):
                    break

        return term_list

    def perform_searches(
        self,
        ai_config,
        header,
        sources,
        territory_id,
        term_list,
        dou_sections: List[str],
        search_date,
        field,
        is_exact_search: Optional[bool],
        ignore_signature_match: Optional[bool],
        force_rematch: Optional[bool],
        full_text: Optional[bool],
        text_length: Optional[int],
        use_summary: Optional[bool],
        ai_search_config: Optional[dict],
        result_as_email: Optional[bool],
        department: List[str],
        department_ignore: List[str],
        terms_ignore: List[str],
        pubtype: List[str],
        excerpt_size: Optional[int],
        number_of_excerpts: Optional[int],
        **context,
    ) -> dict:
        """Performs the search in each source and merge the results"""
        if "DOU" in sources:
            dou_result = self.searchers["DOU"].exec_search(
                term_list=term_list,
                dou_sections=dou_sections,
                search_date=search_date,
                field=field,
                is_exact_search=is_exact_search,
                ignore_signature_match=ignore_signature_match,
                force_rematch=force_rematch,
                department=department,
                department_ignore=department_ignore,
                terms_ignore=terms_ignore,
                pubtype=pubtype,
                reference_date=get_trigger_date(context, local_time=True),
            )
        elif "INLABS" in sources:
            terms = self._parse_term_list(term_list)
            inlabs_result = self.searchers["INLABS"].exec_search(
                ai_config=ai_config,
                terms=terms,
                dou_sections=dou_sections,
                search_date=search_date,
                department=department,
                department_ignore=department_ignore,
                terms_ignore=terms_ignore,
                ignore_signature_match=ignore_signature_match,
                full_text=full_text,
                text_length=text_length,
                use_summary=use_summary,
                ai_search_config=ai_search_config,
                pubtype=pubtype,
                reference_date=get_trigger_date(context, local_time=True),
            )

        if "QD" in sources:
            qd_result = self.searchers["QD"].exec_search(
                territory_id=territory_id,
                term_list=term_list,
                is_exact_search=is_exact_search,
                reference_date=get_trigger_date(context, local_time=True),
                excerpt_size=excerpt_size,
                number_of_excerpts=number_of_excerpts,
                result_as_email=result_as_email,
            )

        if "DOU" in sources and "QD" in sources:
            result = merge_results(qd_result, dou_result)
        elif "INLABS" in sources and "QD" in sources:
            result = merge_results(qd_result, inlabs_result)
        elif "DOU" in sources:
            result = dou_result
        elif "INLABS" in sources:
            result = inlabs_result
        else:
            result = qd_result

        # Add more specs info
        search_dict = {}
        search_dict["result"] = result
        search_dict["header"] = header
        search_dict["sources"] = sources
        search_dict["department"] = department
        search_dict["department_ignore"] = department_ignore
        search_dict["pubtype"] = pubtype

        return search_dict

    def get_xcom_pull_tasks(self, num_searches, **context):
        """Retrieve XCom values from multiple tasks and append them to a new list.
        Function required for Airflow version 2.10.0 or later
        (https://github.com/apache/airflow/issues/41983).
        """
        search_results = []
        for counter in range(1, num_searches + 1):
            search_results.append(
                context["ti"].xcom_pull(task_ids=f"exec_searchs.exec_search_{counter}")
            )

        return search_results

    def has_matches(self, num_searches: int, skip_null: bool, **context) -> str:
        """Check if search has matches and return to skip notification or not"""

        if skip_null:
            search_results = self.get_xcom_pull_tasks(
                num_searches=num_searches, **context
            )

            skip_notification = True

            for search in search_results:
                items = ["contains" for k, v in search["result"].items() if v]
                if items:
                    skip_notification = False
            return "skip_notification" if skip_notification else "send_notification"
        else:
            return "send_notification"

    def send_notification(
        self, num_searches: int, specs: DAGConfig, report_date: str, **context
    ) -> dict:
        """Send user notification using class Notifier"""
        search_report = self.get_xcom_pull_tasks(num_searches=num_searches, **context)

        notifier = Notifier(specs)
        ti = context.get("ti") or context.get("task_instance")
        execution_data = None
        if ti:
            execution_data = ti.xcom_pull(task_ids="persist_analytics")

        hook = AnalyticsMariaDBHook(conn_id=self.ANALYTICS_CONN_ID, database=None)

        try:
            delivery_results = notifier.send_notification(
                search_report=search_report, report_date=report_date
            ) or []
        except Exception as exc:
            if execution_data and execution_data.get("id_execucao"):
                hook.update_execution_delivery(
                    id_execucao=int(execution_data["id_execucao"]),
                    qt_resultados_enviados=0,
                    fl_email_enviado=0,
                    fl_csv_anexado=0,
                    id_status_execucao=10,
                    cd_state_airflow="failed",
                    tx_erro_resumido=str(exc),
                    dh_fim=datetime.now(),
                )
            raise

        email_result = next(
            (
                result
                for result in delivery_results
                if isinstance(result, dict) and result.get("channel") == "email"
            ),
            None,
        )
        any_delivery = any(
            isinstance(result, dict) and result.get("sent") for result in delivery_results
        )
        qt_resultados_total = int((execution_data or {}).get("qt_resultados_total", 0))
        qt_resultados_enviados = qt_resultados_total if any_delivery else 0
        fl_email_enviado = int(bool(email_result and email_result.get("sent")))
        fl_csv_anexado = int(bool(email_result and email_result.get("csv_attached")))

        if execution_data and execution_data.get("id_execucao"):
            hook.update_execution_delivery(
                id_execucao=int(execution_data["id_execucao"]),
                qt_resultados_enviados=qt_resultados_enviados,
                fl_email_enviado=fl_email_enviado,
                fl_csv_anexado=fl_csv_anexado,
                id_status_execucao=9,
                cd_state_airflow="success",
                dh_fim=datetime.now(),
            )
            if any_delivery and qt_resultados_enviados > 0:
                hook.mark_execution_results_sent(id_execucao=int(execution_data["id_execucao"]))

        return {
            "delivery_results": delivery_results,
            "qt_resultados_enviados": qt_resultados_enviados,
            "fl_email_enviado": fl_email_enviado,
            "fl_csv_anexado": fl_csv_anexado,
        }

    def persist_analytics(self, num_searches: int, specs: DAGConfig, **context) -> dict:
        """
        Persist INLABS execution analytics into TB_CLIPPING_EXECUCAO*.

        The execution row is created before notification and updated after the
        notification task finishes.
        """
        ti = context.get("ti") or context.get("task_instance")
        dag_run = context.get("dag_run")
        logical_date = context.get("logical_date")

        if not ti or not dag_run or not logical_date:
            logging.warning("Missing Airflow context for analytics persistence.")
            return

        trigger_date = get_trigger_date(context, local_time=True).date()
        if isinstance(specs.owner, list):
            if len(specs.owner) == 1:
                owner = specs.owner[0]
            else:
                logging.warning("Multiple owners found for DAG %s; storing joined value.", specs.id)
                owner = ",".join(specs.owner)
        else:
            owner = str(specs.owner)

        dry_run_env = os.getenv("RODOU_ANALYTICS_DRY_RUN", "false")
        logging.info(f"DEBUG: RODOU_ANALYTICS_DRY_RUN env var = '{dry_run_env}'")
        analytics_dry_run = (
            dry_run_env.strip().lower()
            in {"1", "true", "yes", "y", "on"}
        )
        logging.info(f"DEBUG: analytics_dry_run = {analytics_dry_run}")

        all_rows = []
        for idx in range(1, num_searches + 1):
            payload = ti.xcom_pull(task_ids=f"exec_searchs.exec_search_{idx}")
            if not payload:
                continue
            sources = payload.get("sources") or []
            if "INLABS" not in sources:
                continue
            all_rows.extend(
                extract_findings(
                    search_payload=payload,
                    dag_id=specs.id,
                    owner=owner,
                    run_id=str(dag_run.run_id),
                    logical_date=logical_date,
                    trigger_date=trigger_date,
                    search_index=idx,
                )
            )

        def _normalize_publication_date(value):
            if value is None:
                return None
            if isinstance(value, date) and not isinstance(value, datetime):
                return value.isoformat()
            if isinstance(value, datetime):
                return value.date().isoformat()
            if isinstance(value, str):
                for fmt in ("%Y-%m-%d", "%d/%m/%Y"):
                    try:
                        return datetime.strptime(value, fmt).date().isoformat()
                    except ValueError:
                        continue
                return value
            return str(value)

        execution_ref = None
        result_rows_by_hash = {}
        for row in all_rows:
            result_hash = build_result_hash(row)
            result_rows_by_hash.setdefault(
                result_hash,
                {
                    "cd_hash_resultado": result_hash,
                    "dt_publicacao": _normalize_publication_date(row.publication_date),
                    "ds_titulo_resultado": row.title,
                    "ds_url_resultado": row.href,
                    "ds_id_publicacao": row.publication_id,
                    "fl_enviado": 0,
                },
            )

        unique_result_rows = list(result_rows_by_hash.values())
        previous_result_hashes = set()

        if analytics_dry_run:
            logging.info(
                "Analytics dry-run enabled. Effective payload (execution + results): %s",
                json.dumps(
                    {
                        "results": unique_result_rows,
                        "meta": {
                            "dag_id": specs.id,
                            "run_id": str(dag_run.run_id),
                            "logical_date": logical_date.isoformat(),
                            "trigger_date": trigger_date.isoformat(),
                            "count_findings": len(all_rows),
                            "count_results": len(unique_result_rows),
                        },
                    },
                    ensure_ascii=False,
                    default=str,
                ),
            )
            return {
                "id_execucao": None,
                "qt_resultados_total": len(unique_result_rows),
                "qt_resultados_enviados": 0,
                "qt_resultados_novos": len(unique_result_rows),
                "qt_resultados_repetidos": 0,
                "fl_possui_resultado": int(bool(unique_result_rows)),
                "fl_email_enviado": 0,
                "fl_csv_anexado": 0,
            }

        hook = AnalyticsMariaDBHook(conn_id=self.ANALYTICS_CONN_ID, database=None)

        execution_ref = hook.resolve_execution_reference(dag_id=specs.id, owner=owner)
        previous_result_hashes = hook.get_previous_result_hashes(
            id_preferencia=execution_ref.id_preferencia,
            dag_id=specs.id,
        )

        current_result_hashes = set(result_rows_by_hash.keys())
        qt_resultados_total = len(unique_result_rows)
        qt_resultados_novos = len(current_result_hashes - previous_result_hashes)
        qt_resultados_repetidos = qt_resultados_total - qt_resultados_novos
        fl_possui_resultado = int(qt_resultados_total > 0)

        id_execucao = hook.insert_execution(
            id_dag_gerada=execution_ref.id_dag_gerada,
            id_preferencia=execution_ref.id_preferencia,
            cd_chave_usuario=owner,
            id_status_execucao=9,
            id_origem_evento=1,
            cd_run_id_airflow=str(dag_run.run_id),
            cd_dag_id_airflow=specs.id,
            cd_state_airflow=getattr(dag_run, "state", None),
            dh_disparo=dag_run.start_date,
            dh_inicio=logical_date,
            dh_fim=logical_date,
            qt_resultados_total=qt_resultados_total,
            qt_resultados_enviados=0,
            qt_resultados_novos=qt_resultados_novos,
            qt_resultados_repetidos=qt_resultados_repetidos,
            fl_possui_resultado=fl_possui_resultado,
            fl_email_enviado=0,
            fl_csv_anexado=0,
        )

        hook.insert_execution_results(id_execucao=id_execucao, rows=unique_result_rows)

        logging.info(
            "Analytics persisted: %s findings, %s unique results.",
            len(all_rows),
            qt_resultados_total,
        )

        return {
            "id_execucao": id_execucao,
            "id_preferencia": execution_ref.id_preferencia,
            "id_dag_gerada": execution_ref.id_dag_gerada,
            "qt_resultados_total": qt_resultados_total,
            "qt_resultados_enviados": 0,
            "qt_resultados_novos": qt_resultados_novos,
            "qt_resultados_repetidos": qt_resultados_repetidos,
            "fl_possui_resultado": fl_possui_resultado,
            "fl_email_enviado": 0,
            "fl_csv_anexado": 0,
        }

    def create_dag(self, specs: DAGConfig, config_file: str) -> DAG:
        """Creates the DAG object and tasks

        Depending on configuration it adds an extra prior task to query
        the term_list from a database
        """
        # Prepare the markdown documentation
        doc_md = self.prepare_doc_md(specs, config_file) if specs.doc_md else None
        # DAG parameters
        default_args = {
            "owner": ",".join(specs.owner),
            "start_date": datetime(2021, 10, 18),
            "depends_on_past": False,
            "retries": 10,
            "retry_delay": timedelta(minutes=2),
            "on_retry_callback": self.on_retry_callback,
            "on_failure_callback": lambda context: self._notify_on_failure(
                specs, context
            ),
        }

        schedule = self._update_schedule(specs)
        dag = DAG(
            specs.id,
            default_args=default_args,
            schedule=schedule,
            description=specs.description,
            doc_md=doc_md,
            catchup=False,
            params={
                "trigger_date": Param(
                    default=date.today().isoformat(), type="string", format="date"
                )
            },
            tags=list(specs.tags),
        )

        with dag:

            with TaskGroup(group_id="exec_searchs") as tg_exec_searchs:

                searches = specs.search

                for counter, subsearch in enumerate(searches, 1):
                    # Verify if the terms were fetched from the database
                    terms_come_from_db: bool = isinstance(
                        subsearch.terms, FetchTermsConfig
                    ) and getattr(subsearch.terms, "from_db_select", None)

                    terms_come_from_airflow_variable: bool = isinstance(
                        subsearch.terms, FetchTermsConfig
                    ) and getattr(subsearch.terms, "from_airflow_variable", None)

                    # determine the terms list
                    term_list = []
                    term_selector = TermSelector()
                    # is it a directly defined list of terms or is it a
                    # configuration for fetching terms from a data source?
                    if subsearch.terms is None:
                        # No specific terms - will search all publications with filters
                        term_list = None
                    elif isinstance(subsearch.terms, list):
                        term_list = subsearch.terms
                    elif terms_come_from_airflow_variable:
                        select_terms_from_airflow_variable_task = PythonOperator(
                            task_id=f"select_terms_from_airflow_variable_{counter}",
                            python_callable=term_selector.select_terms_from_airflow_variable,
                            op_kwargs={
                                "variable": subsearch.terms.from_airflow_variable
                            },
                        )
                        term_list = (
                            "{{ ti.xcom_pull(task_ids='exec_searchs.select_terms_from_airflow_variable_"
                            + str(counter)
                            + "') }}"
                        )

                    elif terms_come_from_db:
                        select_terms_from_db_task = PythonOperator(
                            task_id=f"select_terms_from_db_{counter}",
                            python_callable=term_selector.select_terms_from_db,
                            op_kwargs={
                                "sql": subsearch.terms.from_db_select.sql,
                                "conn_id": subsearch.terms.from_db_select.conn_id,
                            },
                        )
                        term_list = (
                            "{{ ti.xcom_pull(task_ids='exec_searchs.select_terms_from_db_"
                            + str(counter)
                            + "') }}"
                        )

                    exec_search_task = PythonOperator(
                        task_id=f"exec_search_{counter}",
                        python_callable=self.perform_searches,
                        op_kwargs={
                            "ai_config": specs.ai_config,
                            # "api_key_var": specs.ai_config.api_key_var,
                            # "model": specs.model,
                            "header": subsearch.header,
                            "sources": subsearch.sources,
                            "territory_id": subsearch.territory_id,
                            "term_list": term_list,
                            "dou_sections": subsearch.dou_sections,
                            "search_date": subsearch.date,
                            "field": subsearch.field,
                            "is_exact_search": subsearch.is_exact_search,
                            "ignore_signature_match": subsearch.ignore_signature_match,
                            "force_rematch": subsearch.force_rematch,
                            "full_text": subsearch.full_text,
                            "text_length": subsearch.text_length,
                            "use_summary": subsearch.use_summary,
                            "ai_search_config": subsearch.ai_search_config,
                            "department": subsearch.department,
                            "department_ignore": subsearch.department_ignore,
                            "terms_ignore": subsearch.terms_ignore,
                            "pubtype": subsearch.pubtype,
                            "excerpt_size": subsearch.excerpt_size,
                            "number_of_excerpts": subsearch.number_of_excerpts,
                            "result_as_email": result_as_html(specs),
                        },
                    )

                    if terms_come_from_airflow_variable:
                        select_terms_from_airflow_variable_task >> exec_search_task

                    if terms_come_from_db:
                        # pylint: disable=pointless-statement
                        select_terms_from_db_task >> exec_search_task

            has_matches_task = BranchPythonOperator(
                task_id="has_matches",
                python_callable=self.has_matches,
                op_kwargs={
                    "num_searches": len(searches),
                    "skip_null": specs.report.skip_null,
                },
            )

            persist_analytics_task = PythonOperator(
                task_id="persist_analytics",
                python_callable=self.persist_analytics,
                op_kwargs={"num_searches": len(searches), "specs": specs},
            )

            skip_notification_task = EmptyOperator(task_id="skip_notification")

            send_notification_task = PythonOperator(
                task_id="send_notification",
                python_callable=self.send_notification,
                op_kwargs={
                    "num_searches": len(searches),
                    "specs": specs,
                    "report_date": template_ano_mes_dia_trigger_local_time,
                },
            )

            # pylint: disable=pointless-statement
            tg_exec_searchs >> persist_analytics_task >> has_matches_task

            has_matches_task >> [send_notification_task, skip_notification_task]


        return dag


# # Run dag generation
DouDigestDagGenerator().generate_dags()
